### ISSUE TITLE
phpunit/phpunit should be dev dependency

### ISSUE THREAD

**Issue by mestremuten** [tajawal/lodash-php#1]
Now it installs phpunit when requiring your package, which leads in a ton os other packages to be installed (all phpunit dependencies).

[https://getcomposer.org/doc/04-schema.md#require-dev](https://getcomposer.org/doc/04-schema.md#require-dev)

**Comment by IbrahimAssad** [comment]
fixed.
 [1.0.10](https://github.com/tajawal/lodash-php/releases/tag/1.0.10)
